version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro #synchronizacja kodu do kontenera w trybie read only
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - SECRET_KEY=dsj7x2odxqctpdclfx28f2zfix2hi8tqdce7qfaqepdclfx287fp7th5btpdclfx28
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30    
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=foobar
    
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db: